from yacs.config import CfgNode as CN
_C = CN()
_C.TRAIN = CN()
_C.TRAIN.DATASET = CN()

_C.TRAIN.SEED=42
_C.TRAIN.DATASET.BATCH_SIZE=1
_C.TRAIN.DATASET.FILENAMES = ["/gs/bs/tga-lab_otm/zliu/VSRD_PP_Sync/train_tsubame_filenames/filename_split64/sub_0.txt"]
_C.TRAIN.DATASET.CLASS_NAMES = ['car']
_C.TRAIN.DATASET.NUMS_OF_WORKERS= 4
_C.TRAIN.DATASET.NUM_SOURCE_FRAMES=16
_C.TRAIN.DATASET.RECTIFICATION=True

_C.TRAIN.DATASET.TARGET_TRANSFORMS = CN()
_C.TRAIN.DATASET.TARGET_TRANSFORMS.IMAGE_SIZE = [376,1408]
_C.TRAIN.DATASET.TARGET_TRANSFORMS.MIN_MASK_AREA_01 = 1
_C.TRAIN.DATASET.TARGET_TRANSFORMS.MIN_MASK_AREA_02 = 128
_C.TRAIN.DATASET.TARGET_TRANSFORMS.MIN_BOX_SIZE = 16


_C.TRAIN.DDP= CN()
_C.TRAIN.DDP.LAUNCHER='torchrun' #"torchrun"
_C.TRAIN.DDP.BACKEND="nccl"
_C.TRAIN.DDP.NUM_DEVICES_PER_PROCESS=1
_C.TRAIN.DDP.PORT=1209


_C.TRAIN.MULTIPROCESSING = CN()
_C.TRAIN.MULTIPROCESSING.START_METHOD="spawn"

_C.TRAIN.DATASET.SOURCE_TRANSFORMS = CN()
_C.TRAIN.DATASET.SOURCE_TRANSFORMS.IMAGE_SIZE = [376,1408]
_C.TRAIN.DATASET.SOURCE_TRANSFORMS.MIN_MASK_AREA_01 = 1
_C.TRAIN.DATASET.SOURCE_TRANSFORMS.MIN_MASK_AREA_02 = 1
_C.TRAIN.DATASET.SOURCE_TRANSFORMS.MIN_BOX_SIZE = 1

_C.TRAIN.VOLUME_RENDERING = CN()
_C.TRAIN.VOLUME_RENDERING.DISTANCE_RANGE=[0.0,100.0]
_C.TRAIN.VOLUME_RENDERING.MAX_SDF_STD_DEVIATION = 1.0
_C.TRAIN.VOLUME_RENDERING.MAX_SDF_UNION_TEMPERATURE = 1.0
_C.TRAIN.VOLUME_RENDERING.MIN_SDF_STD_DEVIATION= 0.1
_C.TRAIN.VOLUME_RENDERING.MIN_SDF_UNION_TEMPERATURE = 0.1
_C.TRAIN.VOLUME_RENDERING.NUM_COARSE_SAMPLES = 100
_C.TRAIN.VOLUME_RENDERING.NUM_FINE_SAMPLES = 100
_C.TRAIN.VOLUME_RENDERING.NUM_RAYS = 1000


_C.TRAIN.LOSS_WEIGHT = CN()
_C.TRAIN.LOSS_WEIGHT.EIKONAL_LOSS=0.01
_C.TRAIN.LOSS_WEIGHT.IOU_PROJECTION_LOSS=0.1
_C.TRAIN.LOSS_WEIGHT.L1_PROJECTION_LOSS=1.0
_C.TRAIN.LOSS_WEIGHT.PHOTOMETRIC_LOSS=0.0
_C.TRAIN.LOSS_WEIGHT.RADIANCE_LOSS=0.0
_C.TRAIN.LOSS_WEIGHT.SILHOUETTE_LOSS=1.0



_C.TRAIN.LOGGING = CN()
_C.TRAIN.LOGGING.CKPT_INTERVALS =500
_C.TRAIN.LOGGING.EVAL_INTERVALS =1
_C.TRAIN.LOGGING.IMAGE_INTERVALS =500
_C.TRAIN.LOGGING.SCALAR_INTERVALS=50


_C.EVAL= CN()
_C.EVAL.SURFACE_RENDERING=CN()
_C.EVAL.SURFACE_RENDERING.BOUNDING_RADIUS=100.0
_C.EVAL.SURFACE_RENDERING.convergence_criteria=0.01
_C.EVAL.SURFACE_RENDERING.NUM_ITERATIONS=1000
_C.EVAL.SURFACE_RENDERING.NUM_RAYS=100
_C.EVAL.SURFACE_RENDERING.PATCH_SIZE=[11,11]
_C.TRAIN.CONFIG = "/home/2/ux04482/Split_Train/VSRD-V2/Optimized_Based/configs/SPLITS64"


# Modifications Here
_C.TRAIN.MODEL_TYPE='VSRDPP_FULL'
_C.TRAIN.OPTIMIZATION_NUM_STEPS=2500
_C.TRAIN.OPTIMIZATION_WARMUP_STEPS=-1
_C.TRAIN.OPTIMIZATION_RESIDUAL_BOX_STEPS=1000

_C.TRAIN.USE_RDF_MODELING=True
_C.TRAIN.USE_DYNAMIC_MASK=True
_C.TRAIN.USE_DYNAMIC_MODELING=True

# Just for testing
_C.TRAIN.DYNAMIC_LABELS_PATH="/gs/bs/tga-lab_otm/zliu/VSRD_PP_Sync/train_tsubame_filenames/dynamic_split64/sub_0.txt"
# selective from 'mlp', 'vector_velocity','scalar_velocity'
_C.TRAIN.DYNAMIC_MODELING_TYPE='vector_velocity'
