from yacs.config import CfgNode as CN

_C = CN()
_C.TRAIN = CN()
_C.TRAIN.DATASET = CN()


_C.TRAIN.DATASET.BATCH_SIZE=1

_C.TRAIN.DATASET.FILENAMES = ["/media/zliu/data12/dataset/KITTI/VSRD_Format/filenames/R50-N16-M128-B16/dynamic_example/example_0000009463.txt"]
_C.TRAIN.DATASET.CLASS_NAMES = ['car']
_C.TRAIN.DATASET.NUMS_OF_WORKERS= 4
_C.TRAIN.DATASET.NUM_SOURCE_FRAMES=16
_C.TRAIN.DATASET.RECTIFICATION=True

_C.TRAIN.DATASET.TARGET_TRANSFORMS = CN()
_C.TRAIN.DATASET.TARGET_TRANSFORMS.IMAGE_SIZE = [376,1408]
_C.TRAIN.DATASET.TARGET_TRANSFORMS.MIN_MASK_AREA_01 = 1
_C.TRAIN.DATASET.TARGET_TRANSFORMS.MIN_MASK_AREA_02 = 128
_C.TRAIN.DATASET.TARGET_TRANSFORMS.MIN_BOX_SIZE = 16

_C.TRAIN.DATASET.SOURCE_TRANSFORMS = CN()
_C.TRAIN.DATASET.SOURCE_TRANSFORMS.IMAGE_SIZE = [376,1408]
_C.TRAIN.DATASET.SOURCE_TRANSFORMS.MIN_MASK_AREA_01 = 1
_C.TRAIN.DATASET.SOURCE_TRANSFORMS.MIN_MASK_AREA_02 = 1
_C.TRAIN.DATASET.SOURCE_TRANSFORMS.MIN_BOX_SIZE = 1


_C.TRAIN.OPTIMIZATION_NUM_STEPS=3000
_C.TRAIN.OPTIMIZATION_WARMUP_STEPS=1000

_C.TRAIN.VOLUME_RENDERING = CN()
_C.TRAIN.VOLUME_RENDERING.DISTANCE_RANGE=[0.0,100.0]
_C.TRAIN.VOLUME_RENDERING.MAX_SDF_STD_DEVIATION = 1.0
_C.TRAIN.VOLUME_RENDERING.MAX_SDF_UNION_TEMPERATURE = 1.0
_C.TRAIN.VOLUME_RENDERING.MIN_SDF_STD_DEVIATION= 0.1
_C.TRAIN.VOLUME_RENDERING.MIN_SDF_UNION_TEMPERATURE = 0.1
_C.TRAIN.VOLUME_RENDERING.NUM_COARSE_SAMPLES = 100
_C.TRAIN.VOLUME_RENDERING.NUM_FINE_SAMPLES = 100
_C.TRAIN.VOLUME_RENDERING.NUM_RAYS = 1000


_C.TRAIN.LOSS_WEIGHT = CN()
_C.TRAIN.LOSS_WEIGHT.EIKONAL_LOSS=0.01
_C.TRAIN.LOSS_WEIGHT.IOU_PROJECTION_LOSS=0.1
_C.TRAIN.LOSS_WEIGHT.L1_PROJECTION_LOSS=1.0
_C.TRAIN.LOSS_WEIGHT.PHOTOMETRIC_LOSS=0.0
_C.TRAIN.LOSS_WEIGHT.RADIANCE_LOSS=0.0
_C.TRAIN.LOSS_WEIGHT.SILHOUETTE_LOSS=1.0


_C.TRAIN.LOGGING = CN()
_C.TRAIN.LOGGING.CKPT_INTERVALS =500
_C.TRAIN.LOGGING.EVAL_INTERVALS =1
_C.TRAIN.LOGGING.IMAGE_INTERVALS =500
_C.TRAIN.LOGGING.SCALAR_INTERVALS=50


_C.EVAL= CN()
_C.EVAL.SURFACE_RENDERING=CN()
_C.EVAL.SURFACE_RENDERING.BOUNDING_RADIUS=100.0
_C.EVAL.SURFACE_RENDERING.convergence_criteria=0.01
_C.EVAL.SURFACE_RENDERING.NUM_ITERATIONS=1000
_C.EVAL.SURFACE_RENDERING.NUM_RAYS=100
_C.EVAL.SURFACE_RENDERING.PATCH_SIZE=[11,11]



_C.TRAIN.CONFIG = "/home/zliu/CVPR25_Detection/VSRD-V2/Optimized_Based/configs"
_C.EVAL.MODELS_PATH="/home/zliu/CVPR25_Detection/VSRD-V2/Optimized_Based/ckpts/with_pseudo_depth_ssl_igevstereo/data_2d_raw/2013_05_28_drive_0006_sync/image_00/data_rect/0000009463/step_3999.pt"
_C.EVAL.RENDERING_SETINGS = CN()
_C.EVAL.RENDERING_SETINGS.rendered_mask_flag =True
_C.EVAL.RENDERING_SETINGS.use_residual_mask = True



# Just for testing
_C.TRAIN.DYNAMIC_LABELS_PATH="/home/zliu/Desktop/CVPR2025/VSRD-V2/data_pre_processing/Dyanmic_Object_Filtering/saved_contents/sync06/dynamic_mask.txt"

_C.TRAIN.MODEL_TYPE='vsrd_pp_vector_velocity_with_pseudo_depth_ssl_igevstereo'


_C.TRAIN.USE_RDF_MODELING=True
_C.TRAIN.USE_DYNAMIC_MASK=True
_C.TRAIN.USE_DYNAMIC_MODELING=True


# selective from 'mlp', 'vector_velocity','scalar_velocity'
_C.TRAIN.DYNAMIC_MODELING_TYPE='vector_velocity'
