_wandb:
    value:
        cli_version: 0.28.0
        e:
            ib5qx5v77nz23jn9poxq67f53pj917cd:
                args:
                    - --config_path
                    - ablation_selective
                    - --device_id
                    - "0"
                    - --ckpt_dirname
                    - /media/zliu/data12/IJCV/vsrdpp/ckpts
                    - --log_dirname
                    - /media/zliu/data12/IJCV/vsrdpp/logs
                    - --out_dirname
                    - /media/zliu/data12/IJCV/vsrdpp/outs
                    - --wandb
                    - --wandb_project
                    - VSRD++
                    - --wandb_name
                    - seq10-debug
                    - --wandb_log_images
                codePath: trainer/train.py
                codePathLocal: train.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "1006450962432"
                        used: "856885108736"
                executable: /home/zliu/IJCV/VSRD_plus_plus/.pixi/envs/default/bin/python
                git:
                    commit: 70115f8c540bf283f92829f78b5404a03ef59aba
                    remote: git@github.com:Magicboomliu/VSRD_plus_plus.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-c5805e8d-14d6-2710-eead-5e985b1f60cc
                host: megumi
                memory:
                    total: "67255812096"
                os: Linux-6.8.0-111-generic-x86_64-with-glibc2.35
                program: /home/zliu/IJCV/VSRD_plus_plus/trainer/train.py
                python: CPython 3.10.13
                root: /home/zliu/IJCV/VSRD_plus_plus/trainer
                startedAt: "2026-07-02T08:14:51.918041Z"
                writerId: ib5qx5v77nz23jn9poxq67f53pj917cd
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 13
                - 15
                - 16
                - 61
            "4": 3.10.13
            "5": 0.28.0
            "12": 0.28.0
            "13": linux-x86_64
config_path:
    value: ablation_selective
dynamic_modeling_type:
    value: vector_velocity
model_type:
    value: with_pseudo_depth_ssl_igevstereo
optimization_num_steps:
    value: 3000
