# 默认层：model / 渲染 / loss
TRAIN:
  SEED: 42
  MODEL_TYPE: vsrdpp_full
  USE_RDF_MODELING: true
  USE_DYNAMIC_MASK: true
  USE_DYNAMIC_MODELING: true
  DYNAMIC_MODELING_TYPE: vector_velocity
  VOLUME_RENDERING:
    DISTANCE_RANGE: [0.0, 100.0]
    MAX_SDF_STD_DEVIATION: 1.0
    MAX_SDF_UNION_TEMPERATURE: 1.0
    MIN_SDF_STD_DEVIATION: 0.1
    MIN_SDF_UNION_TEMPERATURE: 0.1
    NUM_COARSE_SAMPLES: 100
    NUM_FINE_SAMPLES: 100
    NUM_RAYS: 1000
  LOSS_WEIGHT:
    EIKONAL_LOSS: 0.01
    IOU_PROJECTION_LOSS: 0.1
    L1_PROJECTION_LOSS: 1.0
    PHOTOMETRIC_LOSS: 0.0
    RADIANCE_LOSS: 0.0
    SILHOUETTE_LOSS: 1.0

EVAL:
  SURFACE_RENDERING:
    BOUNDING_RADIUS: 100.0
    convergence_criteria: 0.01
    NUM_ITERATIONS: 1000
    NUM_RAYS: 100
    PATCH_SIZE: [11, 11]
  MODELS_PATH: ""
  RENDERING_SETINGS:
    rendered_mask_flag: true
    use_residual_mask: true
