# 默认层：优化超参
TRAIN:
  OPTIMIZATION_NUM_STEPS: 3000
  OPTIMIZATION_WARMUP_STEPS: -1
  OPTIMIZATION_RESIDUAL_BOX_STEPS: 1000
  DDP:
    LAUNCHER: torchrun
    BACKEND: nccl
    NUM_DEVICES_PER_PROCESS: 1
    PORT: 1209
  MULTIPROCESSING:
    START_METHOD: spawn
